import Finiteness.Evaluation
import Finiteness.Finite
import Finiteness.NeSublists
import Finiteness.Permute
import Finiteness.Pieces
import Finiteness.PrettyPrinting
import Finiteness.Similarity
import Finiteness.Simplifications
import Finiteness.StepsNotIdem
import Finiteness.SubsetUpTo
import Finiteness.SymbolicDerivative
import Finiteness.TTerm
